const Data=[
    {
        image:"/assets/events/carr.png",
        littledescription:"La nouvelle voiture électrique de XYZ Motors vient de sortir ! Avec une autonomie remarquable et des fonctionnalités de pointe, elle promet de révolutionner l'industrie. Découvrez vite ses caractéristiques avant-gardistes sur notre site !",
        title:'Chery fait son entrée sur le marché avec son SUV le plus luxueux', 
        description:"Lorem ipsum dolor sit amet  Est laboriosam quia ea porro quod et galisum recusandae sit illum quas et quia enim  Sit ipsam delectus ut voluptas quia ut laudantium illo in ducimus aspernatur ut ullam cumque ut quas dolorem ut omnis tempore . Ut repellat doloribus ut voluptatem ipsum et quaerat laborum aut deserunt quaerat  Ut voluptatem facere ut nesciunt mollitia qui similique internos sit nostrum laudantium  Sit perferendis laborum et consequatur praesentium et minus ipsum . Est nihil numquam id sapiente quibusdam quo officiis dignissimos ea itaque delectus quo impedit aliquid cum voluptatum officiis aut accusantium itaque  Ut laboriosam sapiente ea natus nihil aut tempora quia aut voluptate voluptates est molestiae nisi! Sed voluptate amet ea sint internos non consequuntur reiciendis in accusantium quidem eos nobis nobis? Et suscipit voluptates non odit ratione eum nisi libero aut nihil impedit aut voluptas eligendi rem tempora voluptas. Aut numquam asperiores id molestiae quasi vel placeat amet ea excepturi reiciendis et nisi earum non assumenda consequatur et error molestiae.",
        Date: "14/23/20",
        id:1,
    },
    {
        image:"/assets/events/carr.png",
        littledescription:"La nouvelle voiture électrique de XYZ Motors vient de sortir ! Avec une autonomie remarquable et des fonctionnalités de pointe, elle promet de révolutionner l'industrie. Découvrez vite ses caractéristiques avant-gardistes sur notre site !",
        title:'Chery fait son entrée sur le marché avec son SUV le plus luxueux', 
        description:"Lorem ipsum dolor sit amet  Est laboriosam quia ea porro quod et galisum recusandae sit illum quas et quia enim  Sit ipsam delectus ut voluptas quia ut laudantium illo in ducimus aspernatur ut ullam cumque ut quas dolorem ut omnis tempore . Ut repellat doloribus ut voluptatem ipsum et quaerat laborum aut deserunt quaerat  Ut voluptatem facere ut nesciunt mollitia qui similique internos sit nostrum laudantium  Sit perferendis laborum et consequatur praesentium et minus ipsum . Est nihil numquam id sapiente quibusdam quo officiis dignissimos ea itaque delectus quo impedit aliquid cum voluptatum officiis aut accusantium itaque  Ut laboriosam sapiente ea natus nihil aut tempora quia aut voluptate voluptates est molestiae nisi! Sed voluptate amet ea sint internos non consequuntur reiciendis in accusantium quidem eos nobis nobis? Et suscipit voluptates non odit ratione eum nisi libero aut nihil impedit aut voluptas eligendi rem tempora voluptas. Aut numquam asperiores id molestiae quasi vel placeat amet ea excepturi reiciendis et nisi earum non assumenda consequatur et error molestiae.",
        Date: "14/23/20",
        id:2,
    },
    {
        image:"/assets/events/carr.png",
        littledescription:"La nouvelle voiture électrique de XYZ Motors vient de sortir ! Avec une autonomie remarquable et des fonctionnalités de pointe, elle promet de révolutionner l'industrie. Découvrez vite ses caractéristiques avant-gardistes sur notre site !",
        title:'Chery fait son entrée sur le marché avec son SUV le plus luxueux', 
        description:"Lorem ipsum dolor sit amet  Est laboriosam quia ea porro quod et galisum recusandae sit illum quas et quia enim  Sit ipsam delectus ut voluptas quia ut laudantium illo in ducimus aspernatur ut ullam cumque ut quas dolorem ut omnis tempore . Ut repellat doloribus ut voluptatem ipsum et quaerat laborum aut deserunt quaerat  Ut voluptatem facere ut nesciunt mollitia qui similique internos sit nostrum laudantium  Sit perferendis laborum et consequatur praesentium et minus ipsum . Est nihil numquam id sapiente quibusdam quo officiis dignissimos ea itaque delectus quo impedit aliquid cum voluptatum officiis aut accusantium itaque  Ut laboriosam sapiente ea natus nihil aut tempora quia aut voluptate voluptates est molestiae nisi! Sed voluptate amet ea sint internos non consequuntur reiciendis in accusantium quidem eos nobis nobis? Et suscipit voluptates non odit ratione eum nisi libero aut nihil impedit aut voluptas eligendi rem tempora voluptas. Aut numquam asperiores id molestiae quasi vel placeat amet ea excepturi reiciendis et nisi earum non assumenda consequatur et error molestiae.",
        Date: "14/23/20",
        id:3,
    },
    {
        image:"/assets/events/carr.png",
        littledescription:"La nouvelle voiture électrique de XYZ Motors vient de sortir ! Avec une autonomie remarquable et des fonctionnalités de pointe, elle promet de révolutionner l'industrie. Découvrez vite ses caractéristiques avant-gardistes sur notre site !",
        title:'Chery fait son entrée sur le marché avec son SUV le plus luxueux', 
        description:"Lorem ipsum dolor sit amet  Est laboriosam quia ea porro quod et galisum recusandae sit illum quas et quia enim  Sit ipsam delectus ut voluptas quia ut laudantium illo in ducimus aspernatur ut ullam cumque ut quas dolorem ut omnis tempore . Ut repellat doloribus ut voluptatem ipsum et quaerat laborum aut deserunt quaerat  Ut voluptatem facere ut nesciunt mollitia qui similique internos sit nostrum laudantium  Sit perferendis laborum et consequatur praesentium et minus ipsum . Est nihil numquam id sapiente quibusdam quo officiis dignissimos ea itaque delectus quo impedit aliquid cum voluptatum officiis aut accusantium itaque  Ut laboriosam sapiente ea natus nihil aut tempora quia aut voluptate voluptates est molestiae nisi! Sed voluptate amet ea sint internos non consequuntur reiciendis in accusantium quidem eos nobis nobis? Et suscipit voluptates non odit ratione eum nisi libero aut nihil impedit aut voluptas eligendi rem tempora voluptas. Aut numquam asperiores id molestiae quasi vel placeat amet ea excepturi reiciendis et nisi earum non assumenda consequatur et error molestiae.",
        Date: "14/23/20",
        id:4,
    },
    {
        image:"/assets/events/carr.png",
        littledescription:"La nouvelle voiture électrique de XYZ Motors vient de sortir ! Avec une autonomie remarquable et des fonctionnalités de pointe, elle promet de révolutionner l'industrie. Découvrez vite ses caractéristiques avant-gardistes sur notre site !",
        title:'Chery fait son entrée sur le marché avec son SUV le plus luxueux', 
        description:"Lorem ipsum dolor sit amet  Est laboriosam quia ea porro quod et galisum recusandae sit illum quas et quia enim  Sit ipsam delectus ut voluptas quia ut laudantium illo in ducimus aspernatur ut ullam cumque ut quas dolorem ut omnis tempore . Ut repellat doloribus ut voluptatem ipsum et quaerat laborum aut deserunt quaerat  Ut voluptatem facere ut nesciunt mollitia qui similique internos sit nostrum laudantium  Sit perferendis laborum et consequatur praesentium et minus ipsum . Est nihil numquam id sapiente quibusdam quo officiis dignissimos ea itaque delectus quo impedit aliquid cum voluptatum officiis aut accusantium itaque  Ut laboriosam sapiente ea natus nihil aut tempora quia aut voluptate voluptates est molestiae nisi! Sed voluptate amet ea sint internos non consequuntur reiciendis in accusantium quidem eos nobis nobis? Et suscipit voluptates non odit ratione eum nisi libero aut nihil impedit aut voluptas eligendi rem tempora voluptas. Aut numquam asperiores id molestiae quasi vel placeat amet ea excepturi reiciendis et nisi earum non assumenda consequatur et error molestiae.",
        Date: "14/23/20",
        id:5,
    },
    {
        image:"/assets/events/carr.png",
        littledescription:"La nouvelle voiture électrique de XYZ Motors vient de sortir ! Avec une autonomie remarquable et des fonctionnalités de pointe, elle promet de révolutionner l'industrie. Découvrez vite ses caractéristiques avant-gardistes sur notre site !",
        title:'Chery fait son entrée sur le marché avec son SUV le plus luxueux', 
        description:"Lorem ipsum dolor sit amet  Est laboriosam quia ea porro quod et galisum recusandae sit illum quas et quia enim  Sit ipsam delectus ut voluptas quia ut laudantium illo in ducimus aspernatur ut ullam cumque ut quas dolorem ut omnis tempore . Ut repellat doloribus ut voluptatem ipsum et quaerat laborum aut deserunt quaerat  Ut voluptatem facere ut nesciunt mollitia qui similique internos sit nostrum laudantium  Sit perferendis laborum et consequatur praesentium et minus ipsum . Est nihil numquam id sapiente quibusdam quo officiis dignissimos ea itaque delectus quo impedit aliquid cum voluptatum officiis aut accusantium itaque  Ut laboriosam sapiente ea natus nihil aut tempora quia aut voluptate voluptates est molestiae nisi! Sed voluptate amet ea sint internos non consequuntur reiciendis in accusantium quidem eos nobis nobis? Et suscipit voluptates non odit ratione eum nisi libero aut nihil impedit aut voluptas eligendi rem tempora voluptas. Aut numquam asperiores id molestiae quasi vel placeat amet ea excepturi reiciendis et nisi earum non assumenda consequatur et error molestiae.",
        Date: "14/23/20",
        id:6,
    },
    {
        image:"/assets/events/carr.png",
        littledescription:"La nouvelle voiture électrique de XYZ Motors vient de sortir ! Avec une autonomie remarquable et des fonctionnalités de pointe, elle promet de révolutionner l'industrie. Découvrez vite ses caractéristiques avant-gardistes sur notre site !",
        title:'Chery fait son entrée sur le marché avec son SUV le plus luxueux', 
        description:"Lorem ipsum dolor sit amet  Est laboriosam quia ea porro quod et galisum recusandae sit illum quas et quia enim  Sit ipsam delectus ut voluptas quia ut laudantium illo in ducimus aspernatur ut ullam cumque ut quas dolorem ut omnis tempore . Ut repellat doloribus ut voluptatem ipsum et quaerat laborum aut deserunt quaerat  Ut voluptatem facere ut nesciunt mollitia qui similique internos sit nostrum laudantium  Sit perferendis laborum et consequatur praesentium et minus ipsum . Est nihil numquam id sapiente quibusdam quo officiis dignissimos ea itaque delectus quo impedit aliquid cum voluptatum officiis aut accusantium itaque  Ut laboriosam sapiente ea natus nihil aut tempora quia aut voluptate voluptates est molestiae nisi! Sed voluptate amet ea sint internos non consequuntur reiciendis in accusantium quidem eos nobis nobis? Et suscipit voluptates non odit ratione eum nisi libero aut nihil impedit aut voluptas eligendi rem tempora voluptas. Aut numquam asperiores id molestiae quasi vel placeat amet ea excepturi reiciendis et nisi earum non assumenda consequatur et error molestiae.",
        Date: "14/23/20",
        id:7,
    },
]
export default Data