// const data = [
//   // {
//   //   Masked: false,
//   //   _id: "second",
//   //   Images: [
//   //     {
//   //       Color: "Red",
//   //       Images: ["../assets/marketplace/redcar.png"],
//   //     },
//   //   ],
//   //   Modele: "Tiggo  8 pro",
//   //   Garentie: "2 years",
//   //   Disponabilite: "Disponible",
//   //   Prix_TTC: 155000,
//   //   Moteur: "Electric",
//   //   PromoObj: {
//   //     IsPromo: true,
//   //     Start: "2022-01-01T00:00:00.000Z",
//   //     End: "2022-12-31T00:00:00.000Z",
//   //     Value: 10,
//   //   },
//   //   MoteurObj: {
//   //     Energie: "Electrique",
//   //     Motricite: "4x4",
//   //     Type_Moteur: "Type X",
//   //     Cylidree: 0,
//   //     Boite: "Auto",
//   //     Consomation: "Low",
//   //     Puissance: 100,
//   //     Nombre_Cylindres: "0",
//   //     Soupapes: 0,
//   //     Accelaration: 2.9,
//   //     Puissance_Tr: 100,
//   //     Turbo: false,
//   //     Nombre_Rapport_Boite: 1,
//   //     Vitesse_Max: 250,
//   //     Couple: 100,
//   //   },
//   //   ConfortObj: {
//   //     Climatisation: "Auto",
//   //     Direction: "Assistee",
//   //     Ecran: "15 inch",
//   //     Accoudoir: "Leather",
//   //     Sieges_Chauffants: true,
//   //     Boire_A_Gants_Refrigerante: false,
//   //     Ordinateur_De__Bord: true,
//   //     Radar_De_Recul: true,
//   //     Autoradio: "Bluetooth",
//   //     bluetooth: true,
//   //   },
//   //   SecurityObj: {
//   //     Airbag: 8,
//   //     Regulateur_Limiteur_de_Vitesse: "Yes",
//   //     Abs: true,
//   //     Keyless: "Yes",
//   //     Esp: true,
//   //     Détecteur_Angle_Mort: true,
//   //     Aide_Demarrage_Cote: true,
//   //     Anti_Demarrage: true,
//   //     Verrouillage_Centralise: "Yes",
//   //     Alarme: "Yes",
//   //   },
//   //   LookObj: {
//   //     Feux_Anti_Arouillard: ["LED"],
//   //     Feux_Avant: "LED",
//   //     Peinture_Metalisee: true,
//   //     Toit: true,
//   //     Vitres_Teintees: true,
//   //     Feux_Jour: "LED",
//   //     Feux_Arriere: "LED",
//   //     Jantes: 20,
//   //     Couleur_Poignees: "Black",
//   //     Dimension_Pneumatique: "235/45 R20",
//   //   },
//   //   VehiculeObj: {
//   //     Volume_Coffre: 500,
//   //     Longueur: 5000,
//   //     Largeur: 2000,
//   //     Hauteur: 1500,
//   //     Empattement: 3000,
//   //     Suspension_Avant: "Independent",
//   //     Suspension_Arriere: "Independent",
//   //     Nombre_Places: 5,
//   //     Nombre_Portes: 4,
//   //     Reservoir: 0,
//   //   },
//   //   createdAt: "2024-03-26T22:40:55.502Z",
//   //   updatedAt: "2024-03-26T22:40:55.502Z",
//   //   __v: 0,
//   // },

//   {

//     img: "../assets/marketplace/bluecar.png",
//     motor: "1.2",
//     reservoir: 90,
//     color: ["Noir", "gris"],
//     energie: "DZL",
//     boite: "manuelle",
//     id: "fqdsfdfsqd",
//     prix: 2999000,
//   },
//   {
//     name: "arizzo 8",
//     img: "../assets/marketplace/greycar.png",
//     motor: "1.4",
//     reservoir: 90,
//     color: ["gris"],
//     energie: "essence",
//     boite: "manuelle",
//     id: "fqdsfdfsqd",
//     prix: 3999000,
//   },
//   {
//     name: "arizzo 8",
//     img: "../assets/marketplace/redcar.png",
//     motor: "2.0",
//     color: ["rouge"],
//     energie: "gas",
//     reservoir: 90,
//     boite: "manuelle",
//     id: "fqdsfdfsqd",
//     prix: 4999000,
//   },
//   {
//     name: "tiggo 8",
//     img: "../assets/marketplace/bluecar.png",
//     motor: "1.2",
//     reservoir: 90,
//     color: ["noir", "gris"],
//     energie: "DZL",
//     boite: "manuelle",
//     id: "fqdsfdfsqd",
//     prix: 2999000,
//   },
//   {
//     name: "arizzo 8",
//     img: "../assets/marketplace/greycar.png",
//     motor: "1.4",
//     reservoir: 90,
//     color: ["gris"],
//     energie: "essence",
//     boite: "manuelle",
//     id: "fqdsfdfsqd",
//     prix: 3999000,
//   },
//   {
//     name: "arizzo 8",
//     img: "../assets/marketplace/redcar.png",
//     motor: "2.0",
//     color: ["rouge"],
//     energie: "gas",
//     reservoir: 90,
//     boite: "manuelle",
//     id: "fqdsfdfsqd",
//     prix: 4999000,
//   },
// ];
// export default data;
const data = [
  {
    Masked: false,
    _id: "second",
    Images: [
      {
        Color: "rouge",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Tiggo  8 pro",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.4",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "essence",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "automatique",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "first",
    Images: [
      {
        Color: "bleu",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Arrizo 6",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.2",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "DZL",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "manuelle",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "second",
    Images: [
      {
        Color: "rouge",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Tiggo  8 pro",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.4",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "essence",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "automatique",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "first",
    Images: [
      {
        Color: "bleu",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Arrizo 6",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.2",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "DZL",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "manuelle",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "second",
    Images: [
      {
        Color: "rouge",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Tiggo  8 pro",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.4",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "essence",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "automatique",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "first",
    Images: [
      {
        Color: "bleu",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Arrizo 6",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.2",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "DZL",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "manuelle",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "second",
    Images: [
      {
        Color: "rouge",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Tiggo  8 pro",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.4",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "essence",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "automatique",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "first",
    Images: [
      {
        Color: "bleu",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Arrizo 6",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.2",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "DZL",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "manuelle",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "second",
    Images: [
      {
        Color: "rouge",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Tiggo  8 pro",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.4",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "essence",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "automatique",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "first",
    Images: [
      {
        Color: "bleu",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Arrizo 6",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.2",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "DZL",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "manuelle",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "second",
    Images: [
      {
        Color: "rouge",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Tiggo  8 pro",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.4",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "essence",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "automatique",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
  {
    Masked: false,
    _id: "first",
    Images: [
      {
        Color: "bleu",
        Images: ["../assets/marketplace/rename.png"],
      },
    ],
    Modele: "Arrizo 6",
    Garentie: "2 years",
    Disponabilite: "Disponible",
    Prix_TTC: 155000,
    Moteur: "1.2",
    PromoObj: {
      IsPromo: true,
      Start: "2022-01-01T00:00:00.000Z",
      End: "2022-12-31T00:00:00.000Z",
      Value: 10,
    },
    MoteurObj: {
      Energie: "DZL",
      Motricite: "4x4",
      Type_Moteur: "Type X",
      Cylidree: 0,
      Boite: "manuelle",
      Consomation: "Low",
      Puissance: 100,
      Nombre_Cylindres: "0",
      Soupapes: 0,
      Accelaration: 2.9,
      Puissance_Tr: 100,
      Turbo: false,
      Nombre_Rapport_Boite: 1,
      Vitesse_Max: 250,
      Couple: 100,
    },
    ConfortObj: {
      Climatisation: "Auto",
      Direction: "Assistee",
      Ecran: "15 inch",
      Accoudoir: "Leather",
      Sieges_Chauffants: true,
      Boire_A_Gants_Refrigerante: false,
      Ordinateur_De__Bord: true,
      Radar_De_Recul: true,
      Autoradio: "Bluetooth",
      bluetooth: true,
    },
    SecurityObj: {
      Airbag: 8,
      Regulateur_Limiteur_de_Vitesse: "Yes",
      Abs: true,
      Keyless: "Yes",
      Esp: true,
      Détecteur_Angle_Mort: true,
      Aide_Demarrage_Cote: true,
      Anti_Demarrage: true,
      Verrouillage_Centralise: "Yes",
      Alarme: "Yes",
    },
    LookObj: {
      Feux_Anti_Arouillard: ["LED"],
      Feux_Avant: "LED",
      Peinture_Metalisee: true,
      Toit: true,
      Vitres_Teintees: true,
      Feux_Jour: "LED",
      Feux_Arriere: "LED",
      Jantes: 20,
      Couleur_Poignees: "Black",
      Dimension_Pneumatique: "235/45 R20",
    },
    VehiculeObj: {
      Volume_Coffre: 500,
      Longueur: 5000,
      Largeur: 2000,
      Hauteur: 1500,
      Empattement: 3000,
      Suspension_Avant: "Independent",
      Suspension_Arriere: "Independent",
      Nombre_Places: 5,
      Nombre_Portes: 4,
      Reservoir: 0,
    },
    createdAt: "2024-03-26T22:40:55.502Z",
    updatedAt: "2024-03-26T22:40:55.502Z",
    __v: 0,
  },
];
export default data;
