const data = [
  {
    name: "arizzo 8",
    img: "../assets/marketplace/bluecar.png",
    motor: "1.2",
    reservoir: 90,
    color: ["Noir", "gris"],
    energie: "DZL",
    boite: "manual",
    id: "fqdsfdfsqd",
    prix: 2999000,
  },
  {
    name: "arizzo 8",
    img: "../assets/marketplace/greycar.png",
    motor: "1.4",
    reservoir: 90,
    color: ["gris"],
    energie: "essence",
    boite: "manual",
    id: "fqdsfdfsqd",
    prix: 3999000,
  },
  {
    name: "arizzo 8",
    img: "../assets/marketplace/redcar.png",
    motor: "2.0",
    color: ["rouge"],
    energie: "gas",
    reservoir: 90,
    boite: "manual",
    id: "fqdsfdfsqd",
    prix: 4999000,
  },
  {
    name: "tiggo 8",
    img: "../assets/marketplace/bluecar.png",
    motor: "1.2",
    reservoir: 90,
    color: ["noir", "gris"],
    energie: "DZL",
    boite: "manual",
    id: "fqdsfdfsqd",
    prix: 2999000,
  },
  {
    name: "arizzo 8",
    img: "../assets/marketplace/greycar.png",
    motor: "1.4",
    reservoir: 90,
    color: ["gris"],
    energie: "essence",
    boite: "manual",
    id: "fqdsfdfsqd",
    prix: 3999000,
  },
  {
    name: "arizzo 8",
    img: "../assets/marketplace/redcar.png",
    motor: "2.0",
    color: ["rouge"],
    energie: "gas",
    reservoir: 90,
    boite: "manual",
    id: "fqdsfdfsqd",
    prix: 4999000,
  },
];
export default data;
