const data = [
  {
    name: "Filtre à huile",
    prix: 150,
    categorie: "Pièces de Moteur",
    modele: ["Tiggo 8", "Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/filtre.png",
    id: 1,
  },
  {
    name: "Radiateur",
    prix: 150,
    categorie: "Pièces de Moteur",
    modele: ["Tiggo 8"],
    etat: "occasion",
    img: "../assets/piece/radiateur.png",
    id: 2,
  },
  {
    name: "Bougies d'allumage",
    prix: 150,
    categorie: "Pièces de Moteur",
    modele: ["Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/bougies.png",
    id: 3,
  },
  {
    name: "pare brise",
    prix: 200,
    categorie: "Pieces de carosserie",
    modele: ["Tiggo 8", "Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/parebris.png",
    id: 4,
  },
  {
    name: "phare",
    prix: 200,
    categorie: "Pieces de carosserie",
    modele: ["Tiggo 8"],
    etat: "occasion",
    img: "../assets/piece/phare.png",
    id: 5,
  },
  {
    name: "Pare-chocs avant",
    prix: 200,
    categorie: "Pieces de carosserie",
    modele: ["Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/pare_choque.png",
    id: 6,
  },
  {
    name: "Siège avant",
    prix: 200,
    categorie: "Pieces d’interieur",
    modele: ["Tiggo 8", "Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/siege.png",
    id: 7,
  },
  {
    name: "Volant",
    prix: 200,
    categorie: "Pieces d’interieur",
    modele: ["Tiggo 8"],
    etat: "occasion",
    img: "../assets/piece/volant.png",
    id: 8,
  },
  {
    name: "Panneau de porte",
    prix: 200,
    categorie: "Pieces d’interieur",
    modele: ["Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/panneau.png",
    id: 9,
  },
];
export default data;
