const data = [
  {
    name: "Filtre à huile",
    prix: 150,
    categorie: "Pièces de Moteur",
    modele: ["Tiggo 8", "Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/filtre.png",
    id: "1",
    reffer: "221007443",
    dispo: false,
    Garentie: "2 an",
    mark: "NGK",
    doc: "",
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
  },
  {
    name: "Radiateur",
    dispo: true,
    prix: 150,
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    categorie: "Pièces de Moteur",
    modele: ["Tiggo 8"],
    etat: "occasion",
    img: "../assets/piece/radiateur.png",
    id: "2",
    reffer: "221007443",
    Garentie: "2 an",
    mark: "NGK",
    doc: "",
  },
  {
    name: "Bougies d'allumage",
    prix: 150,
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    dispo: true,
    categorie: "Pièces de Moteur",
    modele: ["Tiggo 7"],
    etat: "neuve",
    Garentie: "2 an",
    img: "../assets/piece/bougies.png",
    id: "3",
    reffer: "221007443",
    mark: "NGK",
    doc: "",
  },
  {
    name: "pare brise",
    prix: 200,
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    dispo: false,
    Garentie: "2 an",
    categorie: "Pieces de carosserie",
    modele: ["Tiggo 8", "Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/parebris.png",
    id: "4",
    reffer: "221007443",
    mark: "NGK",
    doc: "",
  },
  {
    name: "phare",
    prix: 200,
    dispo: false,
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    categorie: "Pieces de carosserie",
    modele: ["Tiggo 8"],
    etat: "occasion",
    Garentie: "2 an",
    img: "../assets/piece/phare.png",
    id: "5",
    reffer: "221007443",
    mark: "NGK",
    doc: "",
  },
  {
    name: "Pare-chocs avant",
    prix: 200,
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    dispo: false,
    categorie: "Pieces de carosserie",
    modele: ["Tiggo 7"],
    Garentie: "2 an",
    etat: "neuve",
    img: "../assets/piece/pare_choque.png",
    id: "6",
    reffer: "221007443",
    mark: "NGK",
    doc: "",
  },
  {
    name: "Siège avant",
    prix: 200,
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    dispo: false,
    categorie: "Pieces d’interieur",
    modele: ["Tiggo 8", "Tiggo 7"],
    etat: "neuve",
    Garentie: "2 an",
    img: "../assets/piece/siege.png",
    id: "7",
    reffer: "221007443",
    mark: "NGK",
    doc: "",
  },
  {
    name: "Volant",
    prix: 200,
    categorie: "Pieces d’interieur",
    modele: ["Tiggo 8"],
    etat: "occasion",
    Garentie: "2 an",
    img: "../assets/piece/volant.png",
    id: "8",
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    reffer: "221007443",
    dispo: true,
    mark: "NGK",
    doc: "",
  },
  {
    name: "Panneau de porte",
    prix: 200,
    Garentie: "2 an",
    desc: "",
    desc: "Les bougies d'allumage NGK BKR5E-11 sont conçues pour offrir une combustion efficace et fiable dans les moteurs à essence. Elles sont fabriquées avec des matériaux de haute qualité pour assurer une performance optimale et une longue durée de vie. Ces bougies d'allumage sont adaptées à une large gamme de véhicules et offrent une étincelle puissante pour un démarrage rapide et une conduite fluide.",
    categorie: "Pieces d’interieur",
    modele: ["Tiggo 7"],
    etat: "neuve",
    img: "../assets/piece/panneau.png",
    id: "9",
    reffer: "221007443",
    dispo: true,
    mark: "NGK",
    doc: "",
  },
];
export default data;
